baseURL = "https://darrylfinktonjr.com/"
locale = "en-us"
title = "Darryl Finkton Jr."
theme = "minimal-author"
enableRobotsTXT = true
enableGitInfo = false
disableKinds = ["taxonomy", "term"]

[params]
  author = "Darryl Finkton Jr."
  description = "Open source ideas on poverty, population, and liberation"
  
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    identifier = "books"
    name = "Books"
    url = "/books/"
    weight = 10
  [[menu.main]]
    identifier = "childrens-books"
    name = "Children's Books"
    url = "/childrens-books/"
    weight = 15
  [[menu.main]]
    identifier = "essays"
    name = "Essays"
    url = "/essays/"
    weight = 20
  [[menu.main]]
    identifier = "articles"
    name = "Articles"
    url = "/articles/"
    weight = 30
  [[menu.main]]
    identifier = "videos"
    name = "Videos"
    url = "/videos/"
    weight = 40
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 60
  [[menu.main]]
    identifier = "work-with-me"
    name = "Work With Me"
    url = "/work-with-me/"
    weight = 70

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML"]
  page = ["HTML"]

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5
